export const MATEN_MERGE_START = "MATEN_MERGE_START";
export const MATEN_MERGE_SUCCESS = "MATEN_MERGE_SUCCESS";
export const MATEN_MERGE_FAILURE = "MATEN_MERGE_FAILURE";
export const MATEN_MERGE_UPDATE = "MATEN_MERGE_UPDATE";